### ISSUE TITLE
Neurify-DAVE expsilon value

### ISSUE THREAD

**Issue by shenw000** [dlshriver/dnnv-benchmarks#1]
I am running DNNF on dnnv-benchmarks/Neurify-DAVE. It requires the parameter --prop.epsilon. Any recommended epsilon value for this experiment?

Thanks,
Weicheng

**Comment by dlshriver** [comment]
The [Neurify paper](https://arxiv.org/pdf/1809.08098.pdf) uses the values 1, 2, 5, 8, and 10. I would start there.

**Comment by shenw000** [comment]
Thank you, Dave!
